name: second-actions
on: workflow_dispatch
jobs:
    helloworld:
        runs-on: ubuntu-latest
        steps:
            - name: hello world
              run: |
                echo "Hello World"
                echo "Bye World"
              