name: demi-workflow
on: workflow_dispatch
jobs:
    first-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Hello World Bye World!
              run: |
                echo "Hello World"
                echo "Bye World"
